# Generated by Django 4.0.3 on 2022-04-05 15:14

import api.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_orderitem_able_to_write_orderitem_review_written'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': '고객 리뷰', 'verbose_name_plural': '고객 리뷰'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='body',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='리뷰 본문'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('review_image'), verbose_name='리뷰 이미지'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='주문 아이템'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rates',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='리뷰 평점'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='리뷰 제목'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
