# Generated by Django 4.0.3 on 2022-03-28 16:32

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, help_text='상품에 대한 간략한 설명', null=True, verbose_name='상품 요약'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='비디오 파일을 올려주세요.', null=True, upload_to=api.utils.FilenameChanger('product_video1'), verbose_name='비디오 파일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='상품에 대한 상세 설명', null=True, verbose_name='상품 상세 설명'),
        ),
    ]
