# Generated by Django 4.0.3 on 2022-03-29 14:52

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_img',
            field=models.ImageField(blank=True, help_text='배너 이미지를 올려 주세요.', null=True, upload_to=api.utils.FilenameChanger('product_banner_image'), verbose_name='배너 이미지'),
        ),
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
