# Generated by Django 4.0.3 on 2022-03-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_parent_alter_category_slug'),
        ('brand', '0002_rename_thumnail_image_brand_thumbnail_image_and_more'),
        ('product', '0004_product_banner_img_product_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='생성하는 상품이 해당하는 브랜드를 선택해 주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand', verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='가장 하위의 카테고리 하나만 골라주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='상품에 대한 상세 설명을 적어주세요.', null=True, verbose_name='상품 상세 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, help_text='상품에 대한 간략한 설명을 적어주세요.', null=True, verbose_name='상품 요약'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.product', verbose_name='상품 옵션'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.CharField(blank=True, help_text='슬러그는 자동으로 생성됩니다.', max_length=255, null=True, unique=True, verbose_name='상품 슬러그'),
        ),
    ]
