# Generated by Django 4.0.3 on 2022-03-30 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wish_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='wish_product', to=settings.AUTH_USER_MODEL, verbose_name='상품 위시리스트'),
        ),
    ]
