# Generated by Django 4.0.3 on 2022-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_wish_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(help_text='슬러그는 자동으로 생성됩니다.', max_length=255, verbose_name='상품 슬러그'),
        ),
    ]
