# Generated by Django 4.0.3 on 2022-04-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_option',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='product.product', verbose_name='상품'),
        ),
    ]
