# Generated by Django 4.0.3 on 2022-04-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariant_product_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='product',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Summernote',
        ),
    ]
