# Generated by Django 4.0.3 on 2022-04-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_summernote_product_delete_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
    ]
