# Generated by Django 4.0.3 on 2022-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_slug_remove_productvariant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='품절일 경우 체크를 해 주세요.', verbose_name='품절 여부'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='품절일 경우 체크를 해 주세요.', verbose_name='품절 여부'),
        ),
    ]
