# Generated by Django 4.0.3 on 2022-04-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='restrict_quantity',
        ),
    ]
