# Generated by Django 4.0.3 on 2022-03-28 15:43

import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='브랜드 슬러그')),
                ('name', models.CharField(help_text='브랜드 이름을 입력해주세요.', max_length=255, verbose_name='브랜드 이름')),
                ('brand_banner', models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('brand_banner'), verbose_name='브랜드 배너 이미지')),
                ('thumnail_image', models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('brand_thumbnail'), verbose_name='브랜드 썸네일 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='브랜드 설명')),
                ('least_price', models.IntegerField(blank=True, help_text='무료 배송을 위한 최소 주문 금액입니다.', null=True, verbose_name='최소 주문 금액')),
                ('shipping_price', models.IntegerField(blank=True, help_text='기본 배송비입니다. 도서 산간 지역 추가 배송비는 자동으로 주문서에 추가됩니다.', null=True, verbose_name='배송비')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_manager', to=settings.AUTH_USER_MODEL, verbose_name='브랜드 담당자')),
                ('wish_brand', models.ManyToManyField(blank=True, null=True, related_name='user_wish_brand', to=settings.AUTH_USER_MODEL, verbose_name='브랜드 위시리스트')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
            },
        ),
    ]
