# Generated by Django 4.0.3 on 2022-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='thumnail_image',
            new_name='thumbnail_image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(help_text='슬러그는 자동으로 생성됩니다.', max_length=255, verbose_name='브랜드 슬러그'),
        ),
    ]
