# Generated by Django 4.0.3 on 2022-04-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_rename_thumnail_image_brand_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
