# Generated by Django 4.0.3 on 2022-04-04 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0003_remove_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='wish_brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='wish_brand', to=settings.AUTH_USER_MODEL, verbose_name='브랜드 위시리스트'),
        ),
    ]
