# Generated by Django 4.0.3 on 2022-03-27 16:55

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일자'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kind',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.FilenameChanger('profile'), verbose_name='프로필 사진'),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
