# Generated by Django 4.0.3 on 2022-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_points_alter_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='SNS 고유 코드'),
        ),
    ]
