# Generated by Django 4.0.3 on 2022-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(max_length=1024, null=True, verbose_name='파이어베이스 토큰'),
        ),
    ]
