# Generated by Django 4.0.3 on 2022-05-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AlterModelOptions(
            name='notificationcomments',
            options={'verbose_name': '공지사항 댓글', 'verbose_name_plural': '공지사항 댓글'},
        ),
    ]
