# Generated by Django 4.0.3 on 2022-03-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리 이름을 입력해주세요.', max_length=255, verbose_name='카테고리 이름')),
                ('slug', models.CharField(max_length=255, verbose_name='카테고리 슬러그')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category.category', verbose_name='부모 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
    ]
