# Generated by Django 4.0.3 on 2022-03-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_parent_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='부모 카테고리가 없는 경우 생략 해 주세요.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='category.category', verbose_name='부모 카테고리'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text='슬러그는 자동으로 생성됩니다.', max_length=255, null=True, verbose_name='카테고리 슬러그'),
        ),
    ]
