# Generated by Django 4.0.3 on 2022-03-29 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_profile_profile_message_remove_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_limit', models.PositiveIntegerField(verbose_name='쿠폰 최대 발급 개수')),
                ('name', models.CharField(help_text='상품 이름을 입력해주세요.', max_length=255, verbose_name='쿠폰 이름')),
                ('slug', models.CharField(max_length=255, verbose_name='쿠폰 슬러그')),
                ('discount_price', models.IntegerField(verbose_name='할인 가격')),
                ('expire_date', models.DateField(verbose_name='쿠폰 만료일자')),
                ('coupon_type', models.CharField(choices=[('BR', '브랜드 쿠폰'), ('CA', '장바구니 쿠폰')], default='BR', max_length=2)),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, through='coupon.CouponUser', to=settings.AUTH_USER_MODEL, verbose_name='쿠폰 사용자'),
        ),
    ]
