# Generated by Django 4.0.3 on 2022-04-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='slug',
        ),
    ]
