# Generated by Django 4.0.3 on 2022-04-05 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0004_alter_brand_wish_brand'),
        ('coupon', '0002_remove_coupon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user_limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_limit',
            field=models.PositiveIntegerField(verbose_name='쿠폰 최대 발급 개수', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='브랜드'),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='used',
            field=models.BooleanField(default=False, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(help_text='쿠폰 이름을 입력해주세요.', max_length=255, verbose_name='쿠폰 이름'),
        )
    ]
