# Generated by Django 4.0.3 on 2022-04-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_slug'),
        ('coupon', '0002_remove_coupon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='브랜드'),
        ),
    ]
