# Generated by Django 4.0.3 on 2022-04-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
