# Generated by Django 4.0.3 on 2022-04-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_remove_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_limit',
            field=models.PositiveIntegerField(blank=True, help_text='수량 제한이 없다면 비어주세요.', null=True, verbose_name='쿠폰 최대 발급 개수'),
        ),
    ]
