# Generated by Django 4.0.3 on 2022-04-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_coupon_coupon_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '쿠폰', 'verbose_name_plural': '쿠폰'},
        ),
    ]
