# Generated by Django 4.0.3 on 2022-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('결제 완료', '결제 완료'), ('배송 중', '배송 중'), ('배송 완료', '배송 완료'), ('취소', '취소')], default='결제 완료', max_length=32, verbose_name='주문 상태'),
        ),
    ]
