# Generated by Django 4.0.3 on 2022-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_status_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='able_to_write',
            field=models.BooleanField(default=False, verbose_name='리뷰 작성 가능 여부'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review_written',
            field=models.BooleanField(default=False, verbose_name='리뷰 작성 여부'),
        ),
    ]
