# Generated by Django 4.0.3 on 2022-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shippingcompany_orderitem_shipping_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='상품 금액'),
        ),
    ]
