# Generated by Django 4.0.3 on 2022-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options_order_created_at_order_is_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcompany',
            name='tel',
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(max_length=64, verbose_name='배송회사 이름'),
        ),
    ]
