# Generated by Django 4.0.3 on 2022-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_shippingcompany_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_shipping_price',
            field=models.PositiveIntegerField(null=True, verbose_name='총 배송비'),
        ),
    ]
