# Generated by Django 4.0.3 on 2022-03-29 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='시/도/군')),
                ('address1', models.CharField(max_length=200, verbose_name='구/동')),
                ('addresss2', models.CharField(max_length=200, verbose_name='세부 주소')),
                ('post_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소',
            },
        ),
    ]
