# Generated by Django 4.0.3 on 2022-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_address1_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
