# Generated by Django 4.0.3 on 2022-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='요구사항')),
            ],
            options={
                'verbose_name': '배송 요청사항',
                'verbose_name_plural': '배송 요청사항',
            },
        ),
    ]
