# Generated by Django 4.0.3 on 2022-04-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariant_product_option_and_more'),
        ('cart', '0002_remove_cartitem_product_cartitem_product_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant', verbose_name='상품 옵션'),
        ),
    ]
