# Generated by Django 4.0.3 on 2022-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=512, verbose_name='콜렉션 아이디')),
                ('name', models.CharField(max_length=512, verbose_name='팝업 이름')),
                ('thumbnail', models.CharField(max_length=1024, verbose_name='콜렉션 이미지 url')),
            ],
            options={
                'verbose_name': '팝업 콜렉션',
                'verbose_name_plural': '팝업 콜렉션',
            },
        ),
    ]
