# Generated by Django 3.2.8 on 2021-12-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_mypagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPageLog',
        ),
    ]
