# Generated by Django 4.0.3 on 2022-05-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0003_delete_mypagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=True, verbose_name='적립 / 사용 여부')),
                ('amount', models.PositiveIntegerField(verbose_name='적립 / 사용 금액')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='적립 / 사용 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 로그',
                'verbose_name_plural': '포인트 로그',
                'ordering': ['-created'],
            },
        ),
    ]
